W:
  W0:
    ip_address: 134.122.15.237
    sshkey: /Users/thebes/.ssh/marius
  W1:
    ip_address: 134.209.43.255
    sshkey: /Users/thebes/.ssh/marius
  W10:
    ip_address: 143.198.16.184
    sshkey: /Users/thebes/.ssh/marius
  W11:
    ip_address: 143.198.16.216
    sshkey: /Users/thebes/.ssh/marius
  W12:
    ip_address: 134.122.4.156
    sshkey: /Users/thebes/.ssh/marius
  W13:
    ip_address: 143.198.24.13
    sshkey: /Users/thebes/.ssh/marius
  W14:
    ip_address: 143.198.24.65
    sshkey: /Users/thebes/.ssh/marius
  W15:
    ip_address: 143.198.24.76
    sshkey: /Users/thebes/.ssh/marius
  W16:
    ip_address: 143.198.20.27
    sshkey: /Users/thebes/.ssh/marius
  W17:
    ip_address: 143.198.28.76
    sshkey: /Users/thebes/.ssh/marius
  W18:
    ip_address: 143.198.28.240
    sshkey: /Users/thebes/.ssh/marius
  W19:
    ip_address: 143.198.18.138
    sshkey: /Users/thebes/.ssh/marius
  W2:
    ip_address: 167.172.28.158
    sshkey: /Users/thebes/.ssh/marius
  W20:
    ip_address: 143.198.18.171
    sshkey: /Users/thebes/.ssh/marius
  W21:
    ip_address: 143.198.18.181
    sshkey: /Users/thebes/.ssh/marius
  W22:
    ip_address: 143.198.18.183
    sshkey: /Users/thebes/.ssh/marius
  W23:
    ip_address: 143.198.26.23
    sshkey: /Users/thebes/.ssh/marius
  W24:
    ip_address: 143.198.11.1
    sshkey: /Users/thebes/.ssh/marius
  W25:
    ip_address: 143.198.26.244
    sshkey: /Users/thebes/.ssh/marius
  W26:
    ip_address: 143.198.22.50
    sshkey: /Users/thebes/.ssh/marius
  W27:
    ip_address: 167.71.91.172
    sshkey: /Users/thebes/.ssh/marius
  W28:
    ip_address: 64.225.13.57
    sshkey: /Users/thebes/.ssh/marius
  W29:
    ip_address: 64.225.7.184
    sshkey: /Users/thebes/.ssh/marius
  W3:
    ip_address: 134.122.11.122
    sshkey: /Users/thebes/.ssh/marius
  W30:
    ip_address: 159.203.166.236
    sshkey: /Users/thebes/.ssh/marius
  W31:
    ip_address: 64.225.29.215
    sshkey: /Users/thebes/.ssh/marius
  W32:
    ip_address: 143.198.30.11
    sshkey: /Users/thebes/.ssh/marius
  W33:
    ip_address: 143.198.30.87
    sshkey: /Users/thebes/.ssh/marius
  W34:
    ip_address: 143.198.17.0
    sshkey: /Users/thebes/.ssh/marius
  W35:
    ip_address: 143.198.17.55
    sshkey: /Users/thebes/.ssh/marius
  W36:
    ip_address: 143.198.17.221
    sshkey: /Users/thebes/.ssh/marius
  W37:
    ip_address: 68.183.159.153
    sshkey: /Users/thebes/.ssh/marius
  W38:
    ip_address: 157.245.119.69
    sshkey: /Users/thebes/.ssh/marius
  W39:
    ip_address: 167.172.228.71
    sshkey: /Users/thebes/.ssh/marius
  W4:
    ip_address: 134.122.11.146
    sshkey: /Users/thebes/.ssh/marius
  W40:
    ip_address: 161.35.186.105
    sshkey: /Users/thebes/.ssh/marius
  W41:
    ip_address: 143.198.25.98
    sshkey: /Users/thebes/.ssh/marius
  W42:
    ip_address: 143.198.25.102
    sshkey: /Users/thebes/.ssh/marius
  W43:
    ip_address: 143.198.21.74
    sshkey: /Users/thebes/.ssh/marius
  W44:
    ip_address: 143.198.29.81
    sshkey: /Users/thebes/.ssh/marius
  W45:
    ip_address: 143.198.29.120
    sshkey: /Users/thebes/.ssh/marius
  W46:
    ip_address: 143.198.29.129
    sshkey: /Users/thebes/.ssh/marius
  W47:
    ip_address: 167.172.255.193
    sshkey: /Users/thebes/.ssh/marius
  W48:
    ip_address: 143.198.29.140
    sshkey: /Users/thebes/.ssh/marius
  W49:
    ip_address: 143.198.29.208
    sshkey: /Users/thebes/.ssh/marius
  W5:
    ip_address: 159.89.183.255
    sshkey: /Users/thebes/.ssh/marius
  W6:
    ip_address: 143.198.7.110
    sshkey: /Users/thebes/.ssh/marius
  W7:
    ip_address: 143.198.7.192
    sshkey: /Users/thebes/.ssh/marius
  W8:
    ip_address: 167.172.230.231
    sshkey: /Users/thebes/.ssh/marius
  W9:
    ip_address: 143.198.16.77
    sshkey: /Users/thebes/.ssh/marius
